# Generated by Django 3.1.3 on 2020-11-22 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Unnamed Course', max_length=100)),
                ('course_code', models.TextField(default='CS-1110', max_length=10)),
                ('start_time', models.TextField(default='2020-08-25 14:00:00', max_length=50)),
                ('end_time', models.TextField(default='2020-08-25 15:15:00', max_length=50)),
                ('weekdays', picklefield.fields.PickledObjectField(default=list, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='SearchClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchChoices', models.TextField(blank=True, default='CS-3240', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SearchPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchChoices', models.CharField(default='major', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField(blank=True, default='Tell us about yourself!', max_length=800)),
                ('importance_of_collaboration', models.IntegerField(default='2')),
                ('openness_to_social_studying', models.CharField(default='Make friends!', max_length=100)),
                ('time_preference_for_studying', models.CharField(default='Morning', max_length=20)),
                ('personal_strengths', models.TextField(blank=True, default='What are you confident in?', max_length=800)),
                ('personal_weaknesses', models.TextField(blank=True, default='What are you weak in?', max_length=800)),
                ('type_of_learner', models.CharField(default='Visual', max_length=25)),
                ('user_major', models.TextField(default='Undeclared', max_length=100)),
                ('twitter_username', models.CharField(blank=True, default='', max_length=40)),
                ('my_schedule_file', models.FileField(default='uploads/basic.ics', upload_to='uploads/')),
                ('classes', picklefield.fields.PickledObjectField(default=list, editable=False)),
                ('class_name', picklefield.fields.PickledObjectField(default=list, editable=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=200)),
                ('where', models.TextField(max_length=100)),
                ('when', models.TextField()),
                ('why', models.TextField(max_length=800)),
                ('subject', models.TextField(default='', max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.course')),
            ],
        ),
    ]
